on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: dreampulse/action-semantic-pull-request@a37dbf1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
